---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    post:
      summary: create a user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: user is created
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/auth_user":
    post:
      summary: check a user
      tags:
      - User
      parameters: []
      responses:
        '201':
          description: user is vaild
          content: {}
        '422':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              required:
              - email
              - password
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 52.229.184.11
